export const Microgaming = [
   {
      gameID: "SMG_wildfireWins",
      gameNameEn: "Wildfire Wins",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_wildfireWins.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_10000Wishes",
      gameNameEn: "10000 Wishes",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_10000Wishes.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_cashNRichesMegaways",
      gameNameEn: "Cash 'N Riches Megaways™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_cashNRichesMegaways.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_auroraWilds",
      gameNameEn: "Aurora Wilds",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_auroraWilds.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_777RoyalWheel",
      gameNameEn: "777 Royal Wheel",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_777RoyalWheel.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_25000Talons",
      gameNameEn: "25000 Talons",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_25000Talons.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_hyperGold",
      gameNameEn: "Hyper Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_hyperGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_highSociety",
      gameNameEn: "High Society",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_highSociety.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_777Surge",
      gameNameEn: "777 Surge",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_777Surge.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_goldenDragons",
      gameNameEn: "Golden Dragons",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_goldenDragons.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_fireForge",
      gameNameEn: "Fire Forge",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_fireForge.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_amazingLinkZeus",
      gameNameEn: "Amazing Link Zeus",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_amazingLinkZeus.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_squealinRiches",
      gameNameEn: "Squealin' Riches",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_squealinRiches.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_megaMoneyMultiplier",
      gameNameEn: "Mega Money Multiplier",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_megaMoneyMultiplier.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_breakDaBankAgain",
      gameNameEn: "Break da Bank Again",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_breakDaBankAgain.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_serengetiGold",
      gameNameEn: "Serengeti Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_serengetiGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_777MegaDeluxe",
      gameNameEn: "777 Mega Deluxe™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_777MegaDeluxe.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_ancientFortunesPoseidonMegaways",
      gameNameEn: "Ancient Fortunes: Poseidon Megaways ™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_ancientFortunesPoseidonMegaways.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyTwinsJackpot",
      gameNameEn: "Lucky Twins Jackpot",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyTwinsJackpot.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_15Tridents",
      gameNameEn: "15 Tridents",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_15Tridents.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_4DiamondBlues",
      gameNameEn: "4 Diamond Blues™ - Megaways™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_4DiamondBlues.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_amazingLinkApollo",
      gameNameEn: "Amazing Link™ Apollo",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_amazingLinkApollo.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_showdownSaloon",
      gameNameEn: "Showdown Saloon",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_showdownSaloon.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyLeprechaunClusters",
      gameNameEn: "Lucky Leprechaun Clusters",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyLeprechaunClusters.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_maskOfAmun",
      gameNameEn: "Mask of Amun",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_maskOfAmun.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_dungeonsAndDiamonds",
      gameNameEn: "Dungeons and Diamonds",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_dungeonsAndDiamonds.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_silverbackMultiplierMountain",
      gameNameEn: "Silverback Multiplier Mountain",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_silverbackMultiplierMountain.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_dragonsBreath",
      gameNameEn: "Dragon's Breath",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_dragonsBreath.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyTwinsWilds",
      gameNameEn: "Lucky Twins Wilds",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyTwinsWilds.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_breakDaBankAgainMegaways",
      gameNameEn: "Break Da Bank Again™ MEGAWAYS™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_breakDaBankAgainMegaways.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_5StarKnockout",
      gameNameEn: "5 Star Knockout",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_5StarKnockout.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_aDarkMatter",
      gameNameEn: "A Dark Matter",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_aDarkMatter.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_ancientFortunesZeus",
      gameNameEn: "Ancient Fortunes: Zeus",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_ancientFortunesZeus.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_adventuresOfDoubloonIsland",
      gameNameEn: "Adventures Of Doubloon Island",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_adventuresOfDoubloonIsland.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_9potsOfGold",
      gameNameEn: "9 Pots of Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_9potsOfGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_retroReelsDiamondGlitz",
      gameNameEn: "Retro Reels - Diamond Glitz",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_retroReelsDiamondGlitz.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_playboyFortunes",
      gameNameEn: "Playboy Fortunes",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_playboyFortunes.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_queenofAlexandria",
      gameNameEn: "Queen of Alexandria™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_queenofAlexandria.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_blazingMammoth",
      gameNameEn: "Blazing Mammoth",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_blazingMammoth.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_9masksOfFire",
      gameNameEn: "9 Masks Of Fire",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_9masksOfFire.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_westernGold",
      gameNameEn: "Western Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_westernGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_aztecFalls",
      gameNameEn: "Aztec Falls",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_aztecFalls.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_diamondKingJackpots",
      gameNameEn: "Diamond King Jackpots",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_diamondKingJackpots.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_fishinPotsOfGold",
      gameNameEn: "Fishin' Pots of Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_fishinPotsOfGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_goldCollector",
      gameNameEn: "Gold Collector",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_goldCollector.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_wweLegendsLinkWin",
      gameNameEn: "WWE Legends: Link & Win",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_wweLegendsLinkWin.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_arkOfRa",
      gameNameEn: "Ark of Ra",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_arkOfRa.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_boltXUP",
      gameNameEn: "Bolt X UP",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_boltXUP.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_treasuresOfLionCity",
      gameNameEn: "Treasures of Lion City",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_treasuresOfLionCity.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_breakDaBankAgainRespin",
      gameNameEn: "Break da Bank Again Respin",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_breakDaBankAgainRespin.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_jurassicParkGold",
      gameNameEn: "Jurassic Park Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_jurassicParkGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_mastersOfValhalla",
      gameNameEn: "Masters of Valhalla",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_mastersOfValhalla.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_cricketStar",
      gameNameEn: "Cricket Star",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_cricketStar.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_assassinMoon",
      gameNameEn: "Assassin Moon",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_assassinMoon.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bookOfOz",
      gameNameEn: "Book of Oz",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bookOfOz.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_diamondEmpire",
      gameNameEn: "Diamond Empire",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_diamondEmpire.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_odinsRiches",
      gameNameEn: "Odin's Riches",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_odinsRiches.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_playboyGoldJackpots",
      gameNameEn: "Playboy Gold Jackpots",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_playboyGoldJackpots.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_treasurePalace",
      gameNameEn: "Treasure Palace",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_treasurePalace.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_kingsOfCrystals",
      gameNameEn: "Kings of Crystals",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_kingsOfCrystals.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_relicSeekers",
      gameNameEn: "Relic Seekers",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_relicSeekers.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_thunderstruckWildLightning",
      gameNameEn: "Thunderstruck Wild Lightning",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_thunderstruckWildLightning.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_wildOrient",
      gameNameEn: "Wild Orient",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_wildOrient.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_wildWildRomance",
      gameNameEn: "Wild Wild Romance",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_wildWildRomance.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_fortuneRush",
      gameNameEn: "Fortune Rush",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_fortuneRush.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_9masksOfFireHyperSpins",
      gameNameEn: "9 Masks of Fire™ HyperSpins™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_9masksOfFireHyperSpins.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_wildScarabs",
      gameNameEn: "Wild Scarabs",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_wildScarabs.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_ReelTalent",
      gameNameEn: "Reel Talent",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_ReelTalent.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_neptunesRichesOceanOfWilds",
      gameNameEn: "Neptune's Riches: Ocean of Wilds",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_neptunesRichesOceanOfWilds.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_wildCatchNew",
      gameNameEn: "Wild Catch (New)",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_wildCatchNew.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_sunTide",
      gameNameEn: "SunTide",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_sunTide.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bookOfKingArthur",
      gameNameEn: "Book of King Arthur",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bookOfKingArthur.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_emeraldGold",
      gameNameEn: "Emerald Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_emeraldGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyfirecracker",
      gameNameEn: "Lucky Firecracker",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyfirecracker.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_burningDesire",
      gameNameEn: "Burning Desire",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_burningDesire.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bigTop",
      gameNameEn: "Big Top",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bigTop.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_circusJugglersJackpots",
      gameNameEn: "Circus Jugglers Jackpots",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_circusJugglersJackpots.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_fruitVSCandy",
      gameNameEn: "Fruit vs Candy",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_fruitVSCandy.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_forgottenIsland",
      gameNameEn: "Forgotten Island",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_forgottenIsland.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_tikiReward",
      gameNameEn: "Tiki Reward",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_tikiReward.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_atlantisRising",
      gameNameEn: "Atlantis Rising",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_atlantisRising.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bookieOfOdds",
      gameNameEn: "Bookie of Odds",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bookieOfOdds.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_catClans",
      gameNameEn: "Cat Clans",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_catClans.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_gopherGold",
      gameNameEn: "Gopher Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_gopherGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bigBoomRiches",
      gameNameEn: "Big Boom Riches",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bigBoomRiches.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_sterlingSilver",
      gameNameEn: "Sterling Silver",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_sterlingSilver.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_divineRichesHelios",
      gameNameEn: "Divine Riches Helios",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_divineRichesHelios.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_solarWilds",
      gameNameEn: "Solar Wilds",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_solarWilds.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_dragonShard",
      gameNameEn: "Dragon Shard",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_dragonShard.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_goldenStallion",
      gameNameEn: "Golden Stallion",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_goldenStallion.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyTwins",
      gameNameEn: "Lucky Twins",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyTwins.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_magicOfSahara",
      gameNameEn: "Magic of Sahara",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_magicOfSahara.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_africaXUP",
      gameNameEn: "Africa X UP™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_africaXUP.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_reelSpinner",
      gameNameEn: "Reel Spinner",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_reelSpinner.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_egyptianTombs",
      gameNameEn: "Egyptian Tombs",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_egyptianTombs.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_alchemyFortunes",
      gameNameEn: "Alchemy Fortunes",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_alchemyFortunes.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_sunQuest",
      gameNameEn: "Sun Quest",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_sunQuest.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_kodiakKingdom",
      gameNameEn: "Kodiak Kingdom",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_kodiakKingdom.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_playboy",
      gameNameEn: "Playboy",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_playboy.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_laraCroftTemplesAndTombs",
      gameNameEn: "Lara Croft: Temples and Tombs",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_laraCroftTemplesAndTombs.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyClucks",
      gameNameEn: "Lucky Clucks",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyClucks.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_queenOfTheCrystalRays",
      gameNameEn: "Queen of the Crystal Rays",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_queenOfTheCrystalRays.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_goldenPrincess",
      gameNameEn: "Golden Princess",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_goldenPrincess.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_summertime",
      gameNameEn: "Summertime",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_summertime.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_jungleJimAndTheLostSphinx",
      gameNameEn: "Jungle Jim and the Lost Sphinx",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_jungleJimAndTheLostSphinx.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyBachelors",
      gameNameEn: "Lucky Bachelors",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyBachelors.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_breakDaBank",
      gameNameEn: "Break da Bank",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_breakDaBank.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_cashCrazy",
      gameNameEn: "Cash Crazy",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_cashCrazy.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_romanovRiches",
      gameNameEn: "Romanov Riches",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_romanovRiches.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_footballStarDeluxe",
      gameNameEn: "Football Star Deluxe",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_footballStarDeluxe.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_amazonKingdom",
      gameNameEn: "Amazon Kingdom",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_amazonKingdom.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_reelGemsDeluxe",
      gameNameEn: "Reel Gems Deluxe",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_reelGemsDeluxe.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_liquidGold",
      gameNameEn: "Liquid Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_liquidGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_ingotsOfCaiShen",
      gameNameEn: "Ingots of Cai Shen",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_ingotsOfCaiShen.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_kingTusk",
      gameNameEn: "King Tusk",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_kingTusk.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_chroniclesOfOlympusXUP",
      gameNameEn: "Chronicles of Olympus X UP",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_chroniclesOfOlympusXUP.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_carnavalJackpot",
      gameNameEn: "Carnaval Jackpot ",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_carnavalJackpot.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_pingPongStar",
      gameNameEn: "Ping Pong Star",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_pingPongStar.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyKoi",
      gameNameEn: "Lucky Koi",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyKoi.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_adventurePalace",
      gameNameEn: "Adventure Palace",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_adventurePalace.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bustTheBank",
      gameNameEn: "Bust the Bank",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bustTheBank.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_carnaval",
      gameNameEn: "Carnaval",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_carnaval.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bookOfOzLockNSpin",
      gameNameEn: "Book of Oz Lock 'N Spin",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bookOfOzLockNSpin.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_silverSeas",
      gameNameEn: "Silver Seas",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_silverSeas.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_kathmandu",
      gameNameEn: "Kathmandu",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_kathmandu.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyLeprechaun",
      gameNameEn: "Lucky Leprechaun",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyLeprechaun.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_legacyOfOz",
      gameNameEn: "Legacy of Oz ™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_legacyOfOz.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_boomPirates",
      gameNameEn: "Boom Pirates",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_boomPirates.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_dragonDance",
      gameNameEn: "Dragon Dance",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_dragonDance.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_emperorOfTheSeaDeluxe",
      gameNameEn: "Emperor of the Sea Deluxe",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_emperorOfTheSeaDeluxe.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_wantedOutlaws",
      gameNameEn: "Wanted Outlaws",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_wantedOutlaws.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_winSumDimSum",
      gameNameEn: "Win Sum Dim Sum",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_winSumDimSum.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_emperorOfTheSea",
      gameNameEn: "Emperor Of The Sea",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_emperorOfTheSea.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_longMuFortunes",
      gameNameEn: "Long Mu Fortunes",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_longMuFortunes.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_cashOfKingdoms",
      gameNameEn: "Cash of Kingdoms",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_cashOfKingdoms.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyZodiac",
      gameNameEn: "Lucky Zodiac",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyZodiac.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_reelGems",
      gameNameEn: "Reel Gems",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_reelGems.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_rhymingReelsHeartsAndTarts",
      gameNameEn: "Rhyming Reels Hearts And Tarts",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_rhymingReelsHeartsAndTarts.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_jadeShuriken",
      gameNameEn: "Jade Shuriken",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_jadeShuriken.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_shamrockHolmes",
      gameNameEn: "Shamrock Holmes Megaways™",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_shamrockHolmes.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_shogunofTime",
      gameNameEn: "Shogun of Time",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_shogunofTime.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_basketballStarDeluxe",
      gameNameEn: "Basketball Star Deluxe",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_basketballStarDeluxe.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_breakAwayLuckyWilds",
      gameNameEn: "Break Away Lucky Wilds",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_breakAwayLuckyWilds.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_abraCatDabra",
      gameNameEn: "AbraCatDabra",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_abraCatDabra.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_exoticCats",
      gameNameEn: "Exotic Cats",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_exoticCats.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_playboyGold",
      gameNameEn: "Playboy Gold",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_playboyGold.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_huangdiTheYellowEmperor",
      gameNameEn: "Huangdi - The Yellow Emperor",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_huangdiTheYellowEmperor.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_basketballStar",
      gameNameEn: "Basketball Star",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_basketballStar.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_theGrandJourney",
      gameNameEn: "The Grand Journey",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_theGrandJourney.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_lionsPride",
      gameNameEn: "Lion's Pride",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_lionsPride.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_titansOfTheSunTheia",
      gameNameEn: "Titans of the Sun - Theia",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_titansOfTheSunTheia.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_fortuneGirl",
      gameNameEn: "Fortune Girl",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_fortuneGirl.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_wickedTalesDarkRed",
      gameNameEn: "Wicked Tales: Dark Red",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_wickedTalesDarkRed.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_mayanPrincess",
      gameNameEn: "Mayan Princess",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_mayanPrincess.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyRichesHyperspins",
      gameNameEn: "Lucky Riches Hyperspins",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyRichesHyperspins.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_dokiDokiParfait",
      gameNameEn: "Doki Doki Parfait",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_dokiDokiParfait.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_aTaleOfElves",
      gameNameEn: "A Tale of Elves",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_aTaleOfElves.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_beautifulBones",
      gameNameEn: "Beautiful Bones",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_beautifulBones.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_girlsWithGunsJungleHeat",
      gameNameEn: "Girls With Guns - Jungle Heat",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_girlsWithGunsJungleHeat.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_avalon",
      gameNameEn: "Avalon",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_avalon.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_secretRomance",
      gameNameEn: "Secret Romance",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_secretRomance.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_forbiddenThrone",
      gameNameEn: "Forbidden Throne",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_forbiddenThrone.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_lifeOfRiches",
      gameNameEn: "Life Of Riches",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_lifeOfRiches.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_dragonz",
      gameNameEn: "Dragonz",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_dragonz.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_tigersEye",
      gameNameEn: "Tiger's Eye",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_tigersEye.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_retroReelsExtremeHeat",
      gameNameEn: "Retro Reels - Extreme Heat",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_retroReelsExtremeHeat.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bikiniParty",
      gameNameEn: "Bikini Party",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bikiniParty.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_immortalRomance",
      gameNameEn: "Immortal Romance",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_immortalRomance.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_jungleJimElDorado",
      gameNameEn: "Jungle Jim - El Dorado",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_jungleJimElDorado.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_coolBuck5Reel",
      gameNameEn: "Cool Buck - 5 Reel",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_coolBuck5Reel.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_ariana",
      gameNameEn: "Ariana",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_ariana.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_reelThunder",
      gameNameEn: "Reel Thunder",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_reelThunder.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_basketballStarWilds",
      gameNameEn: "Basketball Star Wilds",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_basketballStarWilds.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_titansOfTheSunHyperion",
      gameNameEn: "Titans of the Sun - Hyperion",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_titansOfTheSunHyperion.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_basketballStaronFire",
      gameNameEn: "Basketball Star on Fire",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_basketballStaronFire.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bananaOdyssey",
      gameNameEn: "Banana Odyssey",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bananaOdyssey.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_bookOfMrsClaus",
      gameNameEn: "Book Of Mrs Claus",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_bookOfMrsClaus.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_boatofFortune",
      gameNameEn: "Boat of Fortune",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_boatofFortune.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_tastyStreet",
      gameNameEn: "Tasty Street",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_tastyStreet.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_mauiMischief",
      gameNameEn: "Maui Mischief",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_mauiMischief.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_oniHunterNightSakura",
      gameNameEn: "Oni Hunter Night Sakura",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_oniHunterNightSakura.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_5ReelDrive",
      gameNameEn: "5 Reel Drive",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_5ReelDrive.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_footballStar",
      gameNameEn: "Football Star",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_footballStar.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luchaLegends",
      gameNameEn: "Lucha Legends",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luchaLegends.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_LegendOftheMoonLovers",
      gameNameEn: "Legend of the Moon Lovers",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_LegendOftheMoonLovers.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_thunderstruck",
      gameNameEn: "Thunderstruck",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_thunderstruck.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_breakAwayUltra",
      gameNameEn: "Break Away Ultra",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_breakAwayUltra.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_agentJaneBlondeMaxVolume",
      gameNameEn: "Agent Jane Blonde Max Volume",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_agentJaneBlondeMaxVolume.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_reelStrike",
      gameNameEn: "Reel Strike",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_reelStrike.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_mysticDreams",
      gameNameEn: "Mystic Dreams",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_mysticDreams.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_springBreak",
      gameNameEn: "Spring Break",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_springBreak.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_breakAwayDeluxe",
      gameNameEn: "Break Away Deluxe",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_breakAwayDeluxe.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_kitsuneAdventure",
      gameNameEn: "Kitsune Adventure",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_kitsuneAdventure.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_rugbyStarDeluxe",
      gameNameEn: "Rugby Star Deluxe",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_rugbyStarDeluxe.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_shanghaiBeauty",
      gameNameEn: "Shanghai Beauty",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_shanghaiBeauty.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_hollyJollyPenguins",
      gameNameEn: "Holly Jolly Penguins",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_hollyJollyPenguins.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_gemsAndDragons",
      gameNameEn: "Gems And Dragons",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_gemsAndDragons.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_agentJaneBlonde",
      gameNameEn: "Agent Jane Blonde",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_agentJaneBlonde.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_cashapillar",
      gameNameEn: "Cashapillar",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_cashapillar.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_centreCourt",
      gameNameEn: "Centre Court",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_centreCourt.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_deckTheHalls",
      gameNameEn: "Deck the Halls",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_deckTheHalls.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_ladiesNite",
      gameNameEn: "Ladies Nite",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_ladiesNite.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_secretAdmirer",
      gameNameEn: "Secret Admirer",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_secretAdmirer.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_luckyLittleGods",
      gameNameEn: "Lucky Little Gods",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_luckyLittleGods.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_wackyPanda",
      gameNameEn: "Wacky Panda",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_wackyPanda.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_lostVegas",
      gameNameEn: "Lost Vegas",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_lostVegas.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_HappyHolidays",
      gameNameEn: "Happy Holidays",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_HappyHolidays.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_dolphinCoast",
      gameNameEn: "Dolphin Coast",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_dolphinCoast.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_fishParty",
      gameNameEn: "Fish Party",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_fishParty.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_badmintonHero",
      gameNameEn: "Badminton Hero",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_badmintonHero.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_silverFang",
      gameNameEn: "Silver Fang",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_silverFang.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_theHeatIsOn",
      gameNameEn: "The Heat Is On",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_theHeatIsOn.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_theRatPack",
      gameNameEn: "The Rat Pack",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_theRatPack.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_stardust",
      gameNameEn: "Stardust",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_stardust.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_ourDaysA",
      gameNameEn: "Our Days",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_ourDaysA.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_whatAHoot",
      gameNameEn: "What A Hoot",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_whatAHoot.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_barBarBlackSheep5Reel",
      gameNameEn: "Bar Bar Black Sheep 5 Reel",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_barBarBlackSheep5Reel.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_actionOpsSnowAndSable",
      gameNameEn: "ActionOps Snow and Sable",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_actionOpsSnowAndSable.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_oniHunterPlus",
      gameNameEn: "Oni Hunter Plus",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_oniHunterPlus.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_tallyHo",
      gameNameEn: "Tally Ho",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_tallyHo.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_retroReels",
      gameNameEn: "Retro Reels",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_retroReels.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_breakAway",
      gameNameEn: "Break Away",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_breakAway.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_dreamDate",
      gameNameEn: "Dream Date",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_dreamDate.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_coolWolf",
      gameNameEn: "Cool Wolf",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_coolWolf.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_beachBabes",
      gameNameEn: "Beach Babes",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_beachBabes.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_stashOfTheTitans",
      gameNameEn: "Stash of the Titans",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_stashOfTheTitans.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_oniHunter",
      gameNameEn: "Oni Hunter",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_oniHunter.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_untamedGiantPanda",
      gameNameEn: "Untamed - Giant Panda",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_untamedGiantPanda.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_rhymingReelsGeorgiePorgie",
      gameNameEn: "Rhyming Reels Georgie Porgie",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_rhymingReelsGeorgiePorgie.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_rugbyStar",
      gameNameEn: "Rugby Star",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_rugbyStar.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
   {
      gameID: "SMG_karaokeParty",
      gameNameEn: "Karaoke Party",
      img: "https://ossimg.bdg123456.com/BDGWin/gamelogo/MG/SMG_karaokeParty.png",
      vendorId: 4,
      vendorCode: "MG",
      imgUrl2: null,
      customGameType: 0,
      provider: "mircrogaming",
   },
];
